#
# arch/loongarch/boot/Makefile
#
# Copyright (C) 2020-2022 Loongson Technology Corporation Limited
#

hostprogs := elf-entry
PHONY += elf-entry
elf-entry: $(obj)/elf-entry
	@:

hostprogs += calc_vmlinuz_load_addr
PHONY += calc_vmlinuz_load_addr
calc_vmlinuz_load_addr: $(obj)/calc_vmlinuz_load_addr
	@:
